### ISSUE TITLE
Super Power earned notification after completing sign up and accessing base of ops for the first time

### ISSUE THREAD

**Issue by nathanverrill** [EvokeNet/humhub#53]
Super Power shouldn't be earned until mission 2 (based on my understanding of point values)

**Comment by Guihrmsfo** [comment]
I believe this issue is fixed, right?
@JayantGandhi

**Comment by JayantGandhi** [comment]
No, still happens when you sign up for the first time and go to the base of operations. The super power is also advancing too quickly (go to my profile and see that I already have level 1 in a super power - which should not be the case). The super power should wait until all the underlying powers advance to level 1 before advancing.

**Comment by JayantGandhi** [comment]
![levels](https://cloud.githubusercontent.com/assets/4398613/17307246/0da2a20c-5802-11e6-8fb3-32e33e0523a0.png)

**Comment by Guihrmsfo** [comment]
Alright, I found what was causing the error and fixed it.
Can you try it one more time just to certify?

**Comment by JayantGandhi** [comment]
Awesome! Looks good.
